= About Anypoint Platform Private Cloud Edition
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

[WARNING]
This product was previously named Anypoint Platform On-Premises Edition. Beginning with the 1.5.1 release, it is named Anypoint Platform Private Cloud Edition.

This topic describes the Anypoint Platform Private Cloud Edition. The Anypoint Platform Private Cloud Edition provides the following application components available in the online version of the https://anypoint.mulesoft.com[Anypoint Platform]:

* Runtime Manager: enables you to track and manage your deployed Mule applications
* API Manager: enables you to manager your registered APIs

Anypoint Platform Private Cloud Edition enables you to run and manage Mule applications on your local servers, using the security policies your system requires. When running Anypoint Platform Private Cloud Edition, MuleSoft systems do not interact with your data. You configure and run the software and maintain all storage, processing and transmission of data.

The Anypoint Platform Private Cloud Edition uses https://www.docker.com/[Docker] and https://kubernetes.io/[Kubernetes] to provides built in high availability and scalability. Although the installation wizard makes it easy for you to install the platform without needing to know about either Docker or Kubernetes, it is important to be familiar with how these work for managing and troubleshooting the platform.

== See Also

* xref:system-requirements.adoc[About Minimum System Requirements]
* xref:prereq-workflow.adoc[Workflow: Install and Verify Prerequisites]
* xref:install-workflow.adoc[Workflow: Install Anypoint Platform Private Cloud Edition]