= To Uninstall and Reinstall Anypoint Private Cloud
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

If you encounter problems during installation, you can attempt to reinstall. Before beginning a new install, ensure that all remnants of the original installation have been removed by performing the following commands on all nodes:

----
# remove installed system components
sudo gravity system uninstall --confirm

# remount and clear platform data
sudo mount /var/lib/gravity
sudo rm -rf /var/lib/gravity/*

# remount and clear platform data
sudo mount /var/lib/gravity/planet/etcd
sudo rm -rf /var/lib/gravity/planet/etcd/*

# remount and clear application data
sudo mount /var/lib/data
sudo rm -rf /var/lib/data/*
----

Depending on the state of the full or partial install that you are replacing, these commands may not completely return the system to an installable state. Before beginning reinstall, ensure that your system is still setup correctly and meets the minimum disk and resource requirements.

== See Also

* xref:prereq-workflow.adoc[Workflow: Install and Verify Prerequisites for Physical Servers]
* xref:install-auto-install.adoc[To Install Anypoint Platform Private Cloud Using Automated Installer]